name: Release module

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Build markdown.lua
        run: ./build.sh

      - name: Release markdown.lua
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: markdown.lua
          files: dist/markdown.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
